name: Build and Push Docker Images to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repo code
      - name: Check out repo
        uses: actions/checkout@v3

      # 2. Azure Login (using the SP credentials in GitHub Secrets)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. ACR Login
      - name: ACR Login
        run: |
          az acr login --name devopsnetworkacr17226

      # 4. Build & push subnet-web
      - name: Build & push subnet-web
        run: |
          docker build -t subnet-calculator-web:latest ./src/subnet_calculator/web
          docker tag subnet-calculator-web:latest devopsnetworkacr17226.azurecr.io/subnet-calculator-web:latest
          docker push devopsnetworkacr17226.azurecr.io/subnet-calculator-web:latest

      # 5. Build & push diag-web
      - name: Build & push diag-web
        run: |
          docker build -t network-diagnostics-web:latest ./src/network_diagnostics/web
          docker tag network-diagnostics-web:latest devopsnetworkacr17226.azurecr.io/network-diagnostics-web:latest
          docker push devopsnetworkacr17226.azurecr.io/network-diagnostics-web:latest

      # 6. Build & push frontend
      - name: Build & push network-frontend
        run: |
          docker build -t network-frontend:latest ./frontend
          docker tag network-frontend:latest devopsnetworkacr17226.azurecr.io/network-frontend:latest
          docker push devopsnetworkacr17226.azurecr.io/network-frontend:latest
